## Example Configuration for Previsto 
---
version: "3.9"
services:
  mongo:
      image: mongo:6
      ports:
        - "27017:27017"
      volumes:
        - './data:/data/db'

  user-service:
    image: docker.io/library/user-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"    
    environment:
      - "spring.data.mongodb.host=mongo"

  books-service:
    image: docker.io/library/books-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      - "spring.data.mongodb.host=mongo"

  frontend:
    image: bookloom-frontend:0.0.1
    ports:
      - "3000:3000"
