## Example Configuration for Previsto 
---
version: "3.9"
services:
  kafka:
      image: apache/kafka:3.8.0

      ports:
        - "9092:9092"

  mongo:
      image: mongo:6
      ports:
        - "27017:27017"
      volumes:
        - './data:/data/db'

